function tests = test_shift_equivariance
tests = functiontests(localfunctions);
end

function testOdeAlignedRelativeErrorSmall(testCase)
    params = make_test_params(struct( ...
        'lags', [], ...
        'n', 6, ...
        'n_a_E', 1, 'n_a_I', 0, ...
        'n_b_E', 0, 'n_b_I', 0));
    esn = SRNN_ESN(params);
    shifts = [2, 5, 10];
    se = measure_shift_equivariance(esn, struct( ...
        'T', 400, ...
        'washout', 80, ...
        'shifts', shifts, ...
        'seed', 1729, ...
        'input_scale', 0.15, ...
        'ode_reltol', 1e-8, ...
        'ode_abstol', 1e-10));

    testCase.verifyTrue(all(se.rel_error_per_shift < 1e-4), ...
        sprintf('ODE rel errors: %s', mat2str(se.rel_error_per_shift', 3)));
end

function testMisalignedControlMuchWorse(testCase)
    params = make_test_params(struct( ...
        'lags', [], ...
        'n', 6, ...
        'n_a_E', 1, 'n_a_I', 0, ...
        'n_b_E', 0, 'n_b_I', 0));
    esn = SRNN_ESN(params);
    opts = struct( ...
        'T', 400, ...
        'washout', 80, ...
        'shifts', 5, ...
        'seed', 1729, ...
        'input_scale', 0.15, ...
        'ode_reltol', 1e-8, ...
        'ode_abstol', 1e-10);
    se = measure_shift_equivariance(esn, opts);

    % Deliberate misalignment: compare without applying the shift offset.
    mis = misaligned_relative_error(esn, opts, 5);
    testCase.verifyGreaterThan(mis, 10 * se.rel_error_per_shift(1), ...
        sprintf('mis=%.3e aligned=%.3e', mis, se.rel_error_per_shift(1)));
end

function testDdeBelowMisalignedControl(testCase)
    params = make_test_params(struct( ...
        'lags', 0.05, ...
        'n', 6, ...
        'n_a_E', 1, 'n_a_I', 0, ...
        'n_b_E', 0, 'n_b_I', 0));
    esn = SRNN_ESN(params);
    opts = struct( ...
        'T', 350, ...
        'washout', 100, ...
        'shifts', 4, ...
        'seed', 1729, ...
        'input_scale', 0.1, ...
        'dde_reltol', 1e-7, ...
        'dde_abstol', 1e-9);
    se = measure_shift_equivariance(esn, opts);
    mis = misaligned_relative_error(esn, opts, 4);

    testCase.verifyLessThan(se.rel_error_per_shift(1), mis / 10, ...
        sprintf('DDE aligned=%.3e mis=%.3e', se.rel_error_per_shift(1), mis));
end

function testNonIntegerShiftErrors(testCase)
    params = make_test_params(struct('lags', []));
    testCase.verifyError(@() measure_shift_equivariance(params, struct('shifts', 1.5)), ...
        'measure_shift_equivariance:NonIntegerShift');
end

function rel = misaligned_relative_error(esn, options, s)
% Same construction as measure_shift_equivariance, but compare without shift.
    T = options.T;
    washout = options.washout;
    seed = options.seed;
    input_scale = options.input_scale;
    baseline = 0;
    max_shift = s;
    prefix = washout + max_shift + 1;

    rng(seed);
    waveform = input_scale * randn(T, 1);
    u_ref = [baseline * ones(prefix, 1); waveform; baseline * ones(max_shift, 1)];
    u_shift = [baseline * ones(prefix + s, 1); waveform; baseline * ones(max_shift - s, 1)];

    run_opts = struct('reset_before', true);
    if isfield(options, 'ode_reltol'); run_opts.ode_reltol = options.ode_reltol; end
    if isfield(options, 'ode_abstol'); run_opts.ode_abstol = options.ode_abstol; end
    if isfield(options, 'dde_reltol'); run_opts.dde_reltol = options.dde_reltol; end
    if isfield(options, 'dde_abstol'); run_opts.dde_abstol = options.dde_abstol; end

    esn.resetState();
    X_ref = esn.runReservoir(u_ref, run_opts);
    esn.resetState();
    X_shift = esn.runReservoir(u_shift, run_opts);

    t0 = washout + 1;
    n = min(size(X_ref, 1), size(X_shift, 1));
    idx = t0:n;
    D = X_shift(idx, :) - X_ref(idx, :); % no shift compensation
    rmse = sqrt(mean(D(:).^2));
    ref_rms = sqrt(mean(X_ref(idx, :).^2, 'all'));
    rel = rmse / (ref_rms + eps);
end
