function tests = test_ode_lyapunov_controls
tests = functiontests(localfunctions);
end

function testDiagonalLinearTwoExponents(testCase)
    % Gate G4: recover every exponent within 0.005
    lam = [-0.3; -1.1];
    A = diag(lam);
    odefun = @(t, x) A * x;
    jacfun = @(t, x) A;
    opts = struct( ...
        'odefun', odefun, ...
        'jacobian_fun', jacfun, ...
        'x0', [1; 0.5], ...
        'T_interval', [0, 40], ...
        'lya_dt', 0.5, ...
        'ode_solver', @ode45, ...
        'ode_options', odeset('RelTol', 1e-9, 'AbsTol', 1e-11), ...
        'compute_benettin', true, ...
        'seed', 2);
    r = lyapunov_spectrum_qr_ode(opts);
    testCase.verifyEqual(r.LE_spectrum(1), max(lam), 'AbsTol', 5e-3);
    testCase.verifyEqual(r.LE_spectrum(2), min(lam), 'AbsTol', 5e-3);
    testCase.verifyEqual(r.LLE_benettin, max(lam), 'AbsTol', 5e-3);
    testCase.verifyLessThan(abs(r.LLE_qr - r.LLE_benettin), 0.02);
end

function testStableNonnormalAsymptoticExponents(testCase)
    % Non-normal but asymptotically stable: LEs = Re(eig(A))
    A = [-1.0, 8.0; 0.0, -0.5];
    true_le = sort(real(eig(A)), 'descend');
    odefun = @(t, x) A * x;
    jacfun = @(t, x) A;
    opts = struct( ...
        'odefun', odefun, ...
        'jacobian_fun', jacfun, ...
        'x0', [0.2; 0.3], ...
        'T_interval', [0, 50], ...
        'lya_dt', 0.5, ...
        'ode_solver', @ode45, ...
        'ode_options', odeset('RelTol', 1e-9, 'AbsTol', 1e-11), ...
        'compute_benettin', true, ...
        'seed', 4);
    r = lyapunov_spectrum_qr_ode(opts);
    testCase.verifyEqual(r.LE_spectrum(1), true_le(1), 'AbsTol', 5e-3);
    testCase.verifyEqual(r.LE_spectrum(2), true_le(2), 'AbsTol', 5e-3);
    testCase.verifyLessThan(abs(r.LLE_qr - r.LLE_benettin), 0.02);
end

function testDelayedUnsupported(testCase)
    A = -eye(2);
    opts = struct( ...
        'odefun', @(t, x) A * x, ...
        'jacobian_fun', @(t, x) A, ...
        'x0', [1; 1], ...
        'T_interval', [0, 5], ...
        'params', struct('lags', 0.2));
    testCase.verifyError(@() lyapunov_spectrum_qr_ode(opts), ...
        'MESN:DelayedLyapunovUnsupported');
    params = make_test_params(struct('lags', 0.05));
    S_out = zeros(10, state_layout(params).n_total);
    t_out = (0:9)' * params.dt;
    testCase.verifyError(@() compute_lyapunov_exponents('qr', S_out, t_out, ...
        params.dt, 1/params.dt, [0, 1], params, odeset(), @ode45, ...
        @(t, S) S, t_out, zeros(params.n, 10)), ...
        'MESN:DelayedLyapunovUnsupported');
end

function testMesnOdeSmokeBenettinQrAgree(testCase)
    params = make_test_params(struct( ...
        'n', 4, 'n_a_E', 0, 'n_a_I', 0, 'n_b_E', 0, 'n_b_I', 0, ...
        'lags', [], 'dt', 0.1, 'level_of_chaos', 0.5));
    layout = state_layout(params);
    params.N_sys_eqs = layout.n_total;
    esn = SRNN_ESN(params);
    esn.resetState();
    T = 400;
    U = 0.02 * randn(RandStream('mt19937ar', 'Seed', 9), T, 1);
    [~, S_hist] = esn.runReservoir(U);
    t_out = (0:T-1)' * params.dt;
    T_interval = [10.0, t_out(end)];
    u_ex = params.W_in * U.';
    u_fun = make_input_interpolant(t_out, u_ex);
    rhs = @(t, S) SRNN_reservoir(t, S, u_fun, params);
    lr = compute_lyapunov_exponents('qr', S_hist, t_out, params.dt, 1/params.dt, ...
        T_interval, params, odeset('RelTol', 1e-7, 'AbsTol', 1e-9), ...
        @ode45, rhs, t_out, u_ex);
    testCase.verifyTrue(isfield(lr, 'LLE_qr'));
    testCase.verifyTrue(isfield(lr, 'LLE_benettin'));
    testCase.verifyTrue(isfinite(lr.LLE_qr));
    testCase.verifyTrue(isfinite(lr.LLE_benettin));
    testCase.verifyLessThan(abs(lr.LLE_qr - lr.LLE_benettin), 0.02);
end

function testPositiveDiagConvention(testCase)
    A = diag([-0.2, -0.8]);
    r = lyapunov_spectrum_qr_ode(struct( ...
        'odefun', @(t, x) A * x, ...
        'jacobian_fun', @(t, x) A, ...
        'x0', [1; 1], ...
        'T_interval', [0, 30], ...
        'lya_dt', 0.4, ...
        'compute_benettin', false));
    testCase.verifyEqual(r.LE_spectrum(1), -0.2, 'AbsTol', 5e-3);
    testCase.verifyEqual(r.LE_spectrum(2), -0.8, 'AbsTol', 5e-3);
    testCase.verifyTrue(all(isfinite(r.segment_durations)));
    testCase.verifyTrue(numel(r.t_lya) == numel(r.segment_durations));
end
