function tests = test_empirical_esp_controls
tests = functiontests(localfunctions);
end

function testStableScalarODEContractsNearKnownRate(testCase)
    lambda = -0.4;
    dt = 0.05;
    T = 400;
    U = zeros(T, 1);
    sim = @(U_in, S0) scalar_ode_traj(U_in, S0, lambda, dt);
    esp = verify_echo_state_property([], U, struct( ...
        'simulate_fn', sim, ...
        'n_state', 1, ...
        'n_ic', 6, ...
        'ic_scale', 1.0, ...
        'washout_steps', 20, ...
        'tail_window', [0.5, 1.0], ...
        'min_tail_points', 30, ...
        'verbose', false, ...
        'ic_seed', 7));
    testCase.verifyEqual(esp.classification, 'empirically_contracting_on_test_set');
    expected = lambda * dt;
    testCase.verifyEqual(esp.slope_mean, expected, 'AbsTol', 0.05 * abs(expected) + 1e-3);
end

function testUnstableScalarODENotContracting(testCase)
    lambda = 0.35;
    dt = 0.05;
    T = 300;
    U = zeros(T, 1);
    sim = @(U_in, S0) scalar_ode_traj(U_in, S0, lambda, dt);
    esp = verify_echo_state_property([], U, struct( ...
        'simulate_fn', sim, ...
        'n_state', 1, ...
        'n_ic', 6, ...
        'ic_scale', 0.2, ...
        'washout_steps', 5, ...
        'tail_window', [0.4, 1.0], ...
        'min_tail_points', 20, ...
        'verbose', false, ...
        'ic_seed', 9));
    testCase.verifyEqual(esp.classification, 'not_contracting_on_test_set');
    testCase.verifyGreaterThan(esp.slope_mean, 0);
end

function testInsufficientDurationInconclusive(testCase)
    lambda = -0.5;
    dt = 0.1;
    T = 30;
    U = zeros(T, 1);
    sim = @(U_in, S0) scalar_ode_traj(U_in, S0, lambda, dt);
    esp = verify_echo_state_property([], U, struct( ...
        'simulate_fn', sim, ...
        'n_state', 1, ...
        'n_ic', 4, ...
        'washout_steps', 20, ...
        'min_tail_points', 50, ...
        'verbose', false));
    testCase.verifyEqual(esp.classification, 'inconclusive');
end

function testNoEspProvenField(testCase)
    lambda = -1;
    dt = 0.1;
    T = 200;
    U = zeros(T, 1);
    sim = @(U_in, S0) scalar_ode_traj(U_in, S0, lambda, dt);
    esp = verify_echo_state_property([], U, struct( ...
        'simulate_fn', sim, 'n_state', 1, 'n_ic', 3, ...
        'washout_steps', 10, 'verbose', false));
    testCase.verifyFalse(isfield(esp, 'esp_holds'));
    testCase.verifyTrue(ismember(esp.classification, { ...
        'empirically_contracting_on_test_set', ...
        'not_contracting_on_test_set', ...
        'inconclusive'}));
end

function X = scalar_ode_traj(U, S0, lambda, dt)
    % Exact samples of dx/dt = lambda * x (input ignored).
    T = size(U, 1);
    t = (0:T-1)' * dt;
    x0 = S0(1);
    X = x0 * exp(lambda * t);
end
