function bundle = compute_seed_matched_baseline_bundle(cfg, base_seed, reference_W_in)
% COMPUTE_SEED_MATCHED_BASELINE_BUNDLE  One NARMA+MG baseline unit per base seed.
%
%   bundle = compute_seed_matched_baseline_bundle(cfg, base_seed, reference_W_in)
%
% Scientific unit: final protocol + fingerprint + base seed + both tasks +
% matched W_in + shared candidate/lambda grids. Independent of adaptation/STD/
% delay/feature mechanism cells. Dale-only references remain feature-specific
% and are attached later per cell.

    if nargin < 3 || isempty(reference_W_in)
        error('compute_seed_matched_baseline_bundle:MissingWin', ...
            'reference_W_in is required.');
    end
    if ~isfield(cfg, 'protocol_fingerprint') || isempty(cfg.protocol_fingerprint)
        error('compute_seed_matched_baseline_bundle:MissingFingerprint', ...
            'cfg.protocol_fingerprint must be finalized before shared baselines.');
    end

    bb = local_get(cfg, 'benchmark_baselines', []);
    if isempty(bb)
        bb = build_matched_task_baselines_config(cfg);
    end
    L = cfg.lengths;
    lambda_grid = resolve_baseline_lambda_grid(struct(), cfg);
    narma_task_seed = base_seed + 20;
    mg_task_seed = base_seed + 30;
    W_in_hash = hash_numeric_array(reference_W_in);

    narma_task = build_narma_task_dataset(struct( ...
        'order', local_get(L, 'narma_order', 10), ...
        'T', L.narma_T, ...
        'washout_steps', L.narma_washout, ...
        'train_ratio', L.train_ratio, ...
        'val_ratio', L.val_ratio, ...
        'seed', narma_task_seed));

    mg_ar_lags = local_get(L, 'mg_ar_lags', 10);
    mg_task = build_mackey_glass_onestep_task_dataset(struct( ...
        'T', L.mg_T, ...
        'discard', L.mg_discard, ...
        'washout_steps', L.mg_washout, ...
        'train_ratio', L.train_ratio, ...
        'val_ratio', L.val_ratio, ...
        'seed', mg_task_seed));

    narma_opts = struct( ...
        'task', 'narma', ...
        'mesn_Win', reference_W_in, ...
        'base_seed', base_seed, ...
        'seed', narma_task_seed, ...
        'feature_mode', 'x', ...
        'lambda_grid', lambda_grid, ...
        'narma_order', narma_task.order, ...
        'model_test_nrmse', NaN, ...
        'benchmark_baselines', bb, ...
        'skip_dale', true, ...
        'skip_comparisons', true, ...
        'task_data_hash', narma_task.task_data_hash, ...
        'split_hash', narma_task.split_hash);
    narma_baselines = compute_matched_onestep_baselines( ...
        narma_task.U, narma_task.Y, narma_task.split, ...
        narma_task.washout_steps, narma_opts);

    mg_opts = struct( ...
        'task', 'mackey_glass_onestep', ...
        'mesn_Win', reference_W_in, ...
        'base_seed', base_seed, ...
        'seed', mg_task_seed, ...
        'feature_mode', 'x', ...
        'lambda_grid', lambda_grid, ...
        'ar_lags', mg_ar_lags, ...
        'model_test_nrmse', NaN, ...
        'benchmark_baselines', bb, ...
        'skip_dale', true, ...
        'skip_comparisons', true, ...
        'task_data_hash', mg_task.task_data_hash, ...
        'split_hash', mg_task.split_hash);
    mg_baselines = compute_matched_onestep_baselines( ...
        mg_task.U, mg_task.Y, mg_task.split, ...
        mg_task.washout_steps, mg_opts);

    [narma_ok, narma_report] = validate_matched_task_baselines( ...
        narma_baselines, 'narma', struct( ...
            'lambda_grid', lambda_grid, ...
            'task_data_hash', narma_task.task_data_hash, ...
            'split_hash', narma_task.split_hash, ...
            'require_dale', false, ...
            'require_comparisons', false));
    [mg_ok, mg_report] = validate_matched_task_baselines( ...
        mg_baselines, 'mackey_glass_onestep', struct( ...
            'lambda_grid', lambda_grid, ...
            'task_data_hash', mg_task.task_data_hash, ...
            'split_hash', mg_task.split_hash, ...
            'require_dale', false, ...
            'require_comparisons', false));

    status = 'ok';
    failure_reasons = {};
    if ~narma_ok
        status = 'failed_required_baseline';
        failure_reasons = [failure_reasons, prepend_task(narma_report.reasons, 'narma')]; %#ok<AGROW>
    end
    if ~mg_ok
        status = 'failed_required_baseline';
        failure_reasons = [failure_reasons, prepend_task(mg_report.reasons, 'mackey_glass')]; %#ok<AGROW>
    end

    identity = struct();
    identity.schema_version = 'seed_matched_baseline_bundle_v1';
    identity.protocol_version = char(bb.protocol_version);
    identity.protocol_tier = char(cfg.protocol_tier);
    identity.protocol_fingerprint = char(cfg.protocol_fingerprint);
    identity.base_seed = base_seed;
    identity.narma_task_seed = narma_task_seed;
    identity.mackey_glass_task_seed = mg_task_seed;
    identity.reservoir_size = size(reference_W_in, 1);
    identity.dt = local_get(cfg.base, 'dt', NaN);
    identity.candidate_grids = struct( ...
        'spectral_radius', bb.conventional_leaky_esn.spectral_radius_candidates(:), ...
        'leak_rate', bb.conventional_leaky_esn.leak_rate_candidates(:), ...
        'input_scaling', bb.conventional_leaky_esn.input_scaling_candidates(:));
    identity.ridge_lambda_grid = lambda_grid(:);
    identity.W_in_hash = W_in_hash;
    identity.narma_task_data_hash = narma_task.task_data_hash;
    identity.narma_split_hash = narma_task.split_hash;
    identity.mackey_glass_task_data_hash = mg_task.task_data_hash;
    identity.mackey_glass_split_hash = mg_task.split_hash;

    bundle = identity;
    bundle.W_in = reference_W_in;
    bundle.narma = struct( ...
        'task', strip_task_arrays(narma_task), ...
        'baselines', narma_baselines, ...
        'validation', narma_report);
    bundle.mackey_glass_onestep = struct( ...
        'task', strip_task_arrays(mg_task), ...
        'baselines', mg_baselines, ...
        'validation', mg_report, ...
        'ar_lags', mg_ar_lags);
    bundle.baseline_result_status = status;
    bundle.failure_reasons = failure_reasons;
    bundle.evaluation_provenance = struct( ...
        'mode', 'executed_shared_seed_bundle', ...
        'test_override_used', false, ...
        'injected', false, ...
        'fixture', false);
    bundle.bundle_id = canonical_sha256(identity);
end

function task_out = strip_task_arrays(task_in)
% Persist hashes/metadata; keep arrays only when needed by consumers in-process.
    task_out = task_in;
    % Keep U/Y in the in-memory bundle for optional debugging; hashes are identity.
end

function reasons = prepend_task(reasons, prefix)
    reasons = reasons(:);
    for i = 1:numel(reasons)
        reasons{i} = sprintf('%s:%s', prefix, reasons{i});
    end
end

function v = local_get(s, name, default)
    if isstruct(s) && isfield(s, name) && ~isempty(s.(name))
        v = s.(name);
    else
        v = default;
    end
end
