function tests = test_benettin_time_window
tests = functiontests(localfunctions);
end

function testRecoversNegativeLambda(testCase)
    lam = -0.5;
    opts = struct( ...
        'odefun', @(t, x) lam * x, ...
        'x0', 1.0, ...
        'T_interval', [0, 40], ...
        'lya_dt', 0.5, ...
        'd0', 1e-6, ...
        'seed', 7, ...
        'ode_solver', @ode45, ...
        'ode_options', odeset('RelTol', 1e-9, 'AbsTol', 1e-11));
    r = benettin_lle_ode(opts);
    testCase.verifyEqual(r.status, 'ok');
    testCase.verifyEqual(r.LLE, lam, 'AbsTol', 2e-3);
end

function testRecoversPositiveLambda(testCase)
    lam = 0.25;
    opts = struct( ...
        'odefun', @(t, x) lam * x, ...
        'x0', 1e-3, ...
        'T_interval', [0, 25], ...
        'lya_dt', 0.4, ...
        'd0', 1e-8, ...
        'seed', 11, ...
        'ode_solver', @ode45, ...
        'ode_options', odeset('RelTol', 1e-9, 'AbsTol', 1e-12));
    r = benettin_lle_ode(opts);
    testCase.verifyEqual(r.status, 'ok');
    testCase.verifyEqual(r.LLE, lam, 'AbsTol', 2e-3);
end

function testPreWindowTransientDoesNotAlterEstimate(testCase)
    % Piecewise linear: unstable before t=5, known rate after.
    % Analysis window starts at 5, so pre-window growth must be excluded.
    lam_post = -0.4;
    odefun = @(t, x) local_piecewise(t, x, lam_post);

    opts_a = struct( ...
        'odefun', odefun, ...
        'x0', 1.0, ...  % state at t=5 (analysis start)
        'T_interval', [5, 45], ...
        'lya_dt', 0.5, ...
        'd0', 1e-6, ...
        'seed', 3, ...
        'ode_solver', @ode45, ...
        'ode_options', odeset('RelTol', 1e-9, 'AbsTol', 1e-11));
    r_a = benettin_lle_ode(opts_a);

    % Different pre-window history: integrate unstable transient to t=5,
    % then analyze the same post-window dynamics.
    [~, Xpre] = ode45(@(t, x) 1.5 * x, [0, 5], 0.01, odeset('RelTol', 1e-9));
    opts_b = opts_a;
    opts_b.x0 = Xpre(end, 1);
    r_b = benettin_lle_ode(opts_b);

    testCase.verifyEqual(r_a.LLE, lam_post, 'AbsTol', 2e-3);
    testCase.verifyEqual(r_b.LLE, lam_post, 'AbsTol', 2e-3);
    testCase.verifyEqual(r_a.LLE, r_b.LLE, 'AbsTol', 1e-3);
end

function testHonorsIntervalStart(testCase)
    % If washout were incorrectly included, LLE would be pulled toward +1.2
    lam_pre = 1.2;
    lam_post = -0.55;
    odefun = @(t, x) (t < 8) * lam_pre * x + (t >= 8) * lam_post * x;

    % Integrate through pre-window to get x(8)
    [~, X] = ode45(odefun, [0, 8], 1e-4, odeset('RelTol', 1e-9));
    opts = struct( ...
        'odefun', odefun, ...
        'x0', X(end, 1), ...
        'T_interval', [8, 48], ...
        'lya_dt', 0.5, ...
        'd0', 1e-6, ...
        'seed', 5, ...
        'ode_solver', @ode45, ...
        'ode_options', odeset('RelTol', 1e-9, 'AbsTol', 1e-11));
    r = benettin_lle_ode(opts);
    testCase.verifyEqual(r.LLE, lam_post, 'AbsTol', 2e-3);
    testCase.verifyGreaterThanOrEqual(min(r.t_lya), 8 - 1e-9);
end

function testZeroSeparationNamedFailure(testCase)
    % Custom solver returns identical fiducial/perturbed endpoints -> d_k = 0
    opts = struct( ...
        'odefun', @(t, x) -x, ...
        'x0', 1.0, ...
        'T_interval', [0, 2], ...
        'lya_dt', 1.0, ...
        'd0', 1e-6, ...
        'seed', 1, ...
        'ode_solver', @collapse_solver);
    testCase.verifyError(@() benettin_lle_ode(opts), 'benettin_lle_ode:NumericalFailure');
end

function testDelayedRejected(testCase)
    opts = struct( ...
        'odefun', @(t, x) -x, ...
        'x0', 1, ...
        'T_interval', [0, 5], ...
        'params', struct('lags', 0.1));
    testCase.verifyError(@() benettin_lle_ode(opts), 'MESN:DelayedLyapunovUnsupported');
end

function dx = local_piecewise(t, x, lam_post)
    if t < 5
        dx = 1.5 * x;
    else
        dx = lam_post * x;
    end
end

function [t, X] = collapse_solver(~, tspan, x0, ~)
    t = [tspan(1); tspan(end)];
    z = zeros(1, numel(x0));
    X = [x0(:).'; z];
end
