function params = make_linear_activation_params(overrides)
% make_linear_activation_params  Small ODE/DDE params with linear activation.
%
% Linear activation phi(q)=q and phi'(q)=1 for analytical forward-model controls.
% Default: n=2, no SFA/STD, empty lags, Dale off, W identity-scaled.

    if nargin < 1
        overrides = struct();
    end

    base = struct( ...
        'n', 2, ...
        'fraction_E', 0.5, ...
        'n_a_E', 0, ...
        'n_a_I', 0, ...
        'n_b_E', 0, ...
        'n_b_I', 0, ...
        'lags', [], ...
        'n_inputs', 1, ...
        'dale', false, ...
        'row_center_W', false, ...
        'weight_rng_seed', 1729, ...
        'input_rng_seed', 1730, ...
        'level_of_chaos', 0.5 ...
    );

    f = fieldnames(overrides);
    for i = 1:numel(f)
        base.(f{i}) = overrides.(f{i});
    end

    params = default_MESN_config(base);
    params.activation_function = @(q) q;
    params.activation_function_derivative = @(q) ones(size(q));
    params = validate_MESN_params(params);
end
